import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
<<<<<<< HEAD
import Navbar from "./component/navbar";
import Footer from "./component/footer";
=======
>>>>>>> 5e89d79 (Initial commit from Create Next App)
=======
import Navbar from "./component/navbar";
import Footer from "./component/footer";
>>>>>>> 4181afb (eslinc)

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 4181afb (eslinc)
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
<<<<<<< HEAD
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 5e89d79 (Initial commit from Create Next App)
=======
>>>>>>> 4181afb (eslinc)
    </html>
  );
}
